### ISSUE TITLE
manta seems to be written for python 2.7

### ISSUE THREAD

**Issue by pierrj** [GooglingTheCancerGenome/sv-callers#61]
Hello, I am running the pipeline on the test data. Here is my snakemake command:

`snakemake -R -C echo_run=0 --use-conda --latency-wait 30 --jobs 14 --cluster "sbatch ## cluster info"
`
Most of the jobs seem to be running okay but I am getting this error for manta

```
Activating conda environment: /global/scratch/pierrj/sv-callers/snakemake/.snakemake/conda/cc58e4b5
++ dirname data/bam/3/T3--N3/manta_out/manta.vcf
+ OUTDIR=data/bam/3/T3--N3/manta_out
++ basename data/bam/3/T3--N3/manta_out/manta.vcf
+ OUTFILE=manta.vcf
+ '[' 0 -eq 1 ']'
+ configManta.py --runDir data/bam/3/T3--N3/manta_out --reference data/fasta/chr22.fasta --tumorBam data/bam/3/T3.bam --normalBam data/bam/3/N3.bam
Traceback (most recent call last):
  File "/global/scratch/pierrj/sv-callers/snakemake/.snakemake/conda/cc58e4b5/bin/configManta.py", line 34, in <module>
    from mantaOptions import MantaWorkflowOptionsBase
  File "/global/scratch/pierrj/sv-callers/snakemake/.snakemake/conda/cc58e4b5/share/manta-1.1.0-0/lib/python/mantaOptions.py", line 32, in <module>
    from configureOptions import ConfigureWorkflowOptions
  File "/global/scratch/pierrj/sv-callers/snakemake/.snakemake/conda/cc58e4b5/share/manta-1.1.0-0/lib/python/configureOptions.py", line 171
    except OptParseException, e :
                            ^
SyntaxError: invalid syntax
```

This seems to be python 2.7 syntax. I checked the manta github and this seems to be the case:
https://github.com/Illumina/manta/blob/master/src/python/bin/configManta.py

Is there something I am missing? It seems that the conda environment in the install instructions (called wf) uses python 3.7, which is the one I have been using. Please let me know if you're aware of this issue and what might help fix the problem. Thanks!

**Comment by pierrj** [comment]
It works now... Not exactly sure what happened but I realized that the main snakemake instance uses a different conda environment than the manta rule uses (still learning snakemake). I guess somehow it wasn't using the proper python but it is now.
