### ISSUE TITLE
Java heap space error while running GRIDSS

### ISSUE THREAD

**Issue by lsantuari** [GooglingTheCancerGenome/sv-callers#66]
I am getting the following error when running GRIDSS on some of the samples of the 1KG dataset:
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at au.edu.wehi.idsv.VcfBreakendSummary.<init>(VcfBreakendSummary.java:120)
        at au.edu.wehi.idsv.IdsvVariantContext.create(IdsvVariantContext.java:70)
        at gridss.cmdline.VcfTransformCommandLineProgram.lambda$getBreakpoints$55(VcfTransformCommandLineProgram.java:59)
        at gridss.cmdline.VcfTransformCommandLineProgram$$Lambda$191/0x00000017c0a05c40.apply(Unknown Source)
        at com.google.common.collect.Iterators$8.transform(Iterators.java:817)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:674)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at com.google.common.collect.Iterators$PeekingImpl.hasNext(Iterators.java:1171)
        at au.edu.wehi.idsv.util.WindowedSortingIterator.advanceUnderlying(WindowedSortingIterator.java:76)
        at au.edu.wehi.idsv.util.WindowedSortingIterator.computeNext(WindowedSortingIterator.java:62)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at au.edu.wehi.idsv.util.AutoClosingIterator.hasNext(AutoClosingIterator.java:48)
        at au.edu.wehi.idsv.SequentialEvidenceAllocator.bufferVariantsBefore(SequentialEvidenceAllocator.java:252)
        at au.edu.wehi.idsv.SequentialEvidenceAllocator.next(SequentialEvidenceAllocator.java:167)
        at au.edu.wehi.idsv.SequentialEvidenceAllocator.next(SequentialEvidenceAllocator.java:43)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:674)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at au.edu.wehi.idsv.util.AutoClosingIterator.hasNext(AutoClosingIterator.java:48)
        at au.edu.wehi.idsv.SequentialCoverageAnnotator.hasNext(SequentialCoverageAnnotator.java:121)
        at au.edu.wehi.idsv.util.ParallelTransformIterator.dispatch(ParallelTransformIterator.java:101)
        at au.edu.wehi.idsv.util.ParallelTransformIterator.next(ParallelTransformIterator.java:94)
        at au.edu.wehi.idsv.util.AutoClosingIterator.next(AutoClosingIterator.java:53)
        at com.google.common.collect.Iterators$PeekingImpl.peek(Iterators.java:1194)
        at au.edu.wehi.idsv.util.WindowedSortingIterator.nextRecordCouldBeAtStartOfWindow(WindowedSortingIterator.java:83)
        at au.edu.wehi.idsv.util.WindowedSortingIterator.advanceUnderlying(WindowedSortingIterator.java:76)
        at au.edu.wehi.idsv.util.WindowedSortingIterator.computeNext(WindowedSortingIterator.java:62)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
```
I recall that the maximum heap space is [capped at 31GB](https://github.com/GooglingTheCancerGenome/sv-callers/blob/300a95ddac3c77a1cac2d9e00051591d0a92292f/snakemake/rules/gridss.smk#L36), so I am not sure if we can increase it. Have you encountered this error before?

**Comment by arnikz** [comment]
Could you provide additional details about the run (e.g., local/Slurm/GE, input sample files)?

**Comment by arnikz** [comment]
This seems related to #1.
